FROM docker
MAINTAINER Christian Godenschwager "christian.godenschwager@fau.de"

RUN curl -SL https://github.com/grammarly/rocker/releases/download/1.1.0/rocker-1.1.0-darwin_amd64.tar.gz | tar -xzC /usr/local/bin && chmod +x /usr/local/bin/rocker
